package cafe.dialed.entities.enums;

public enum BasketType {
    STANDARD_DOUBLE, STANDARD_SINGLE, PRECISION_DOUBLE, PRECISION_SINGLE, PRECISION_TRIPLE, DOUBLE_WALLED_SINGLE, DOUBLE_WALLED_DOUBLE, UNKNOWN
}
